name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
      - name: Check Xcode Command Line Tools
        run: xcrun --version
      - name: Check Available Simulator Runtimes
        run: xcrun simctl list runtimes
      - name: Check Available Simulator Devices
        run: xcrun simctl list devices
      # - name: Boot Simulator
      #   run: |
      #     xcrun simctl list devices -j | jq -r '.devices["com.apple.CoreSimulator.SimRuntime.iOS-18-1"][] | select(.name == "iPad Pro 11-inch (M4)") | .udid' | xargs -I {} xcrun simctl boot {}
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: List available SDKs
        run: xcodebuild -showsdks
      - name: Build
        run: |
          xcodebuild build \
            -scheme GenkouYoushi \
            -destination "platform=iOS Simulator,OS=18.1,name=iPad Pro 11-inch (M4)"
      # - name: Test
      #   run: |
      #     xcodebuild test \
      #       -scheme GenkouYoushi \
      #       -sdk iphonesimulator18.1 \
      #       -destination "platform=iOS Simulator,OS=18.1,name=iPad Pro 11-inch (M4)"
      - name: Archive
        run: |
          xcodebuild clean archive \
            -scheme GenkouYoushi \
            -configuration Release \
            -sdk iphoneos18.1 \
            -destination generic/platform=iOS \
            -archivePath GenkouYoushi.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_STYLE=Manual
